In [1]:
# import modules 
import geopandas as gdp 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [4]:
X.columns

Index(['COUNTRY', 'NUTS2', 'NUTS3', 'CODE', 'CODE_NUTS2', 'CODE_NUTS3',
       'POPULATION', 'POP_DENS', 'POP>=60', '%POP>=60', 'FEMEALES', '%FEMEALS',
       'POP 0-14', 'POP 15-29', 'POP 30-44', 'POP 45-59', 'POP_GROWTH',
       'HOUSEHOLDS', 'DWELLINGS', 'SURFACE AREA', 'UNEM_R', 'D_MEDICALE',
       'COPD %', 'Respiratory dis mortality', 'Smokers %', 'Diabetes %',
       'Diabetes mortality', 'Cardiovascular dis mortality',
       'BEDS_Intcare/reanim', 'COVID19_D', 'COVID_Mortality_R',
       'COVID19_CCONF', 'COVID_Cases_R', 'COVID19_TESTS', 'DURATION_LD (days)',
       'Lag_1stCase-LD (days)', 'LD_SEVEIRTY_W1', 'LD_SEVEIRTY_W2',
       'LD_SEVEIRTY_W3', 'LD_SEVEIRTY_W4', 'LD_SEVEIRTY_W5', 'LD_SEVEIRTY_W6',
       'LD_SEVEIRTY_W7', 'LD_SEVEIRTY_W8', 'LD_SEVEIRTY_W9', 'LD_SEVEIRTY_W10',
       'LD_SEVEIRTY_W11', 'LD_SEVEIRTY_W12', 'LD_SEVEIRTY_W13',
       'LD_SEVEIRTY_W14', 'LD_SEVEIRTY_W15', 'LD_SEVEIRTY_W16',
       'LD_SEVEIRTY_W17', 'LD_SEVEIRTY_W18', 'LD_SEVEIRTY_W19',
       'LD_SEVEIRTY_W20', 'LD_SEVEIRTY_W21', 'LD_SEVEIRTY_W22',
       'LD_SEVEIRTY_W23', 'LD_SEVEIRTY_W24', 'LD_SEVEIRTY_W25',
       'LD_SEVEIRTY_W26', 'LD_SEVEIRTY_W27', 'LD_SEVEIRTY_W28',
       'LD_SEVEIRTY_W29', 'LD_SEVEIRTY_W30', 'LD_SEVEIRTY_W31',
       'LD_SEVEIRTY_W32', 'LD_SEVEIRTY_W33', 'LD_SEVEIRTY_W34',
       'LD_SEVEIRTY_W35', 'NO2_avg', 'WIND_Avg', 'Temp_mean_over12yrs',
       'NTL_avg', 'PRESSURE_avg', 'PRECIPITATION', 'SOLAR_RAD_avg', 'LAI_avg'],
      dtype='object')

In [6]:
# read data 
X = pd.read_excel('Input/Xis.xlsx', sheet_name = 'Data').drop(['COVID19_CCONF', 'COVID_Cases_R', 'COVID19_TESTS'], axis = 1)
X

,COUNTRY,NUTS2,NUTS3,CODE,CODE_NUTS2,CODE_NUTS3,POPULATION,POP_DENS,POP>=60,%POP>=60,...,LD_SEVEIRTY_W34,LD_SEVEIRTY_W35,NO2_avg,WIND_Avg,Temp_mean_over12yrs,NTL_avg,PRESSURE_avg,PRECIPITATION,SOLAR_RAD_avg,LAI_avg
0,Austria,-,-,AT,-,-,8971664,107.1,2239965.0,24.967108,...,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Austria,Burgenland,-,AT,AT11,-,297048,NaN,87107.0,29.324217,...,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Austria,Burgenland,Mittelburgenland,AT,AT11,AT111,37899,54.0,12030.0,31.742262,...,0.0,0,2.630771,3.000289,9.207416,8.241319,0.923921,57.232225,11746.180873,1.790256
3,Austria,Burgenland,Nordburgenland,AT,AT11,AT112,161164,90.0,44838.0,27.821350,...,0.0,0,2.630771,3.175656,10.078024,12.364236,0.964879,49.182485,11775.125172,1.447596
4,Austria,Burgenland,SÃ¼dburgenland,AT,AT11,AT113,97985,67.0,30239.0,30.860846,...,0.0,0,2.151366,2.412818,9.107134,9.802083,0.940495,62.468139,11758.273024,1.877442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1466,United Kingdom,Northern Ireland,Causeway Coast and Glens,UK,UKN0,UKN12,145286,73.0,34646.0,23.846757,...,1.0,1,1.467555,5.260761,8.876803,8.998803,0.954414,109.720370,8835.869048,2.323968
1467,United Kingdom,Northern Ireland,Antrim and Newtownabbey,UK,UKN0,UKN13,143664,198.0,31598.0,21.994376,...,1.0,1,1.467555,4.480453,9.042322,23.145833,0.961360,85.517360,8908.740962,1.794279
1468,United Kingdom,Northern Ireland,Lisburn and Castlereagh,UK,UKN0,UKN14,145856,288.0,33225.0,22.779317,...,1.0,1,1.467555,4.815490,8.898968,25.309896,0.969130,79.688079,8935.650675,2.056716
1469,United Kingdom,Northern Ireland,Mid and East Antrim,UK,UKN0,UKN15,139867,134.0,34601.0,24.738502,...,1.0,1,1.467555,5.324285,8.642288,13.358796,0.942485,92.498278,8848.130693,2.375605
1470,United Kingdom,Northern Ireland,Fermanagh and Omagh,UK,UKN0,UKN16,117763,39.0,26595.0,22.583494,...,1.0,1,1.294444,3.962490,9.120348,6.865278,0.975407,118.027034,8939.303797,2.578789