In [1]:
import pandas as pd

In [18]:
s = pd.read_excel('Ireland.xlsx', sheet_name = 'Unpivoted').drop(['UNIT', 'STATISTIC'], axis =1)
s['Quarter'] = s['Quarter'].apply(lambda x: x[:4])
s.groupby(['Quarter', 'Region']).mean().unstack().T.reset_index().drop('level_0', axis =1).to_csv('Ireland-done.csv')

In [7]:
s

,STATISTIC,Quarter,Region,UNIT,VALUE
0,ILO Unemployment Rate (15 - 74 years),2019,State,%,4.8
1,ILO Unemployment Rate (15 - 74 years),2019,Northern and Western,%,4.8
2,ILO Unemployment Rate (15 - 74 years),2019,Border,%,3.9
3,ILO Unemployment Rate (15 - 74 years),2019,West,%,5.5
4,ILO Unemployment Rate (15 - 74 years),2019,Southern,%,5.2
...,...,...,...,...,...
91,ILO Unemployment Rate (15 - 74 years),2020,South-West,%,6.6
92,ILO Unemployment Rate (15 - 74 years),2020,Eastern and Midland,%,6.0
93,ILO Unemployment Rate (15 - 74 years),2020,Dublin,%,6.4
94,ILO Unemployment Rate (15 - 74 years),2020,Mid-East,%,5.2
95,ILO Unemployment Rate (15 - 74 years),2020,Midland,%,6.0