In [1]:
import pandas as pd

In [9]:
ref = pd.read_excel('Referenz Gemeinden-GVB-Kreise_NUTS.xlsx', skiprows = 1)
ref['Gemeinden 31.12.2017'] = ref['Gemeinden 31.12.2017'].apply(lambda x: str(x)[:-3])
ref.head(3)

,Gemeinden 31.12.2017,Unnamed: 1,Zentralörtliche Einstufung (ja/nein),Unnamed: 3,Zentralörltiche Einstufung (4er Kategorie),Unnamed: 5,Zentralörtliche Einstufung differenziert,Unnamed: 7,Fäche in km²,Einwohner 31.12.2017,Bundesland,Unnamed: 11,West/Ost,Unnamed: 13,Raumtyp nach Lage,Unnamed: 15,Stadt-/Gemeindetyp,Unnamed: 17
0,1001,"Flensburg, Stadt",1,Zentraler Ort,1,Oberzentrum und höher,10,Oberzentrum,56.74,88519,1,Schleswig-Holstein,1,West,2,zentral,20,Mittelstadt
1,1002,"Kiel, Landeshauptstadt",1,Zentraler Ort,1,Oberzentrum und höher,10,Oberzentrum,118.65,247943,1,Schleswig-Holstein,1,West,2,zentral,10,Großstadt
2,1003,"Lübeck, Hansestadt",1,Zentraler Ort,1,Oberzentrum und höher,10,Oberzentrum,214.21,216318,1,Schleswig-Holstein,1,West,1,sehr zentral,10,Großstadt

In [8]:
tar = pd.read_excel('All table.xlsx')[['NUTS_ID', 'NUTS_NAME']]
tar

    NUTS_ID                                       NUTS_NAME
0        DG                                     Deutschland
1        01                              Schleswig-Holstein
2     01001                     Flensburg, kreisfreie Stadt
3     01002        Kiel, Landeshauptstadt, kreisfreie Stadt
4     01003            Lübeck, Hansestadt, kreisfreie Stadt
..      ...                                             ...
533   16073                      Saalfeld-Rudolstadt, Kreis
534   16074                            Saale-Holzland-Kreis
535   16075                                Saale-Orla-Kreis
536   16076                                    Greiz, Kreis
537   16077                         Altenburger Land, Kreis

[538 rows x 2 columns]