In [1]:
# read modules 

import pandas as pd

In [3]:
# read the the dataset 
ds = pd.read_excel('../../02_Data/03_Explanatory varibales/Output/Xis.xlsx')
ds

,NUTS_ID,POPULATION_2019,POP_DENS_2019,POP>=60_2019,%POP>=60_2019,FEMEALES_2018,%FEMEALS_2019,POP 0-14_2019,POP 15-29_2019,POP 30-44_2019,...,C_first_wave,C_second_wave,C_third_wave,D_first_wave,D_second_wave,D_third_wave,M_first_wave,M_second_wave,M_third_wave,Typology
0,BG423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,10217.0,7083.0,NaN,NaN,NaN,-44.0,1344.4,483.0,intermediate
1,BG424,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,3977.0,2461.0,NaN,NaN,NaN,-6.4,558.8,166.4,predominantly rural
2,BG425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,4146.0,2091.0,NaN,NaN,NaN,1.2,669.0,247.4,predominantly rural
3,CH011,802965.0,276.0,172276.0,21.454982,408618.0,50.888644,129682.0,154695.0,173840.0,...,5277.0,72924.0,0.0,291.0,699.0,0.0,369.6,674.0,12.0,intermediate
4,CH012,345051.0,66.0,87492.0,25.356252,174125.0,50.463555,50223.0,62745.0,67311.0,...,1857.0,34129.0,10516.0,125.0,525.0,22.0,158.4,455.4,23.6,intermediate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4702,Viana do Castelo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4703,Vila Real,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4704,Viseu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4705,Ã‰vora,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4706,UK_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 1. Data curation

# 2. Spatial economotrics models

## 1.1 Ordinary Least Squares (OLS)

## 1.2 Spatial Autoregressive model (SAR)

## 1.3 Spatial Error Model (SEM)

## 1.4 Spatial Autoregressive Confused (SAC)

In [ ]:
#